language: ko-KR
reviews:
  profile: assertive
  high_level_summary: true
  review_status: true
  request_changes_workflow: false
  auto_review:
    enabled: true
    drafts: true
  path_filters:
    - "!deprecated/**"
chat:  
  auto_reply: true