rootProject.name = 'TripNow'
include("common:core")
include("common:api")
include("common:db")
include("post-service")
include("search-service")
include("web-api-service")
//include("board")
//include("sign")
include("discovery-service")
include("api-gateway")
//include("logpipeline")
//include("comment")
//include("favorite")
//include("bff")
//include("realtimepopular")
//include("monitoring")
