rootProject.name = 'TripNow'
include("common-module:core")
include("common-module:api")
include("common-module:db")
include("post-service")
include("board")
include("sign")
include("discovery")
include("gateway")
include("logpipeline")
include("comment")
include("favorite")
include("bff")
include("realtimepopular")
include("monitoring")
