server:
  port: 8000

spring:
  application:
    name: api-gateway

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  web:
    resources:
      add-mappings: true

  cloud:
    gateway:
      routes:
        - id: web-api-service-guest
          uri: lb://web-api-service
          predicates:
            - Path=/api/v1/search/**, /api/v1/web-api/v3/api-docs/**

        - id: web-api-service-user
          uri: lb://web-api-service
          predicates:
            - Path=/api/v1/posts/**, /api/v1/comments/**, /api/v1/likes/**, /api/v1/search/*/me
          filters:
            - name: JwtAuthenticationFilter

        - id: post-service-docs
          uri: lb://post-service
          predicates:
            - Path=/v1/posts/v3/api-docs/**

        - id: search-service-docs
          uri: lb://search-service
          predicates:
            - Path=/v1/search/v3/api-docs/**


      httpclient:
        connect-timeout: 5000
        response-timeout: 5s

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
            allowCredentials: true


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVERS:http://localhost:8761}/eureka

#security key
springboot:
  jwt:
    secret: ${JWT_SECRET_KEY:V2hhdElzTG92ZUJhYnlob250aHVydG1lbm9tb3JlMTIzNDU2Nzg5MDEyMzQ=}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Web Api Service
        url: /api/v1/web-api/v3/api-docs/web-api-service
      - name: Post Service Docs
        url: /v1/posts/v3/api-docs/post-service
      - name: Search Service Docs
        url: /v1/search/v3/api-docs/search-service
