spring:
  config:
    activate:
      on-profile: prod

  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000 # 빠른 연결 실패 유도
        response-timeout: 3s
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "https://tmp-domain.com"
            allowedHeaders: [ "Content-Type", "Authorization" ]
            allowedMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
            allowCredentials: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false