server:
  port: 8000

spring:
  application:
    name: api-gateway

  config:
    import: optional:file:api-gateway/.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  web:
    resources:
      add-mappings: true

  cloud:
    gateway:
      routes:
        - id: web-api-service-signup
          uri: lb://web-api-service
          predicates:
            - Path=/api/v1/members
            - Method=POST

        - id: web-api-service-guest
          uri: lb://web-api-service
          predicates:
            - Path=/api/v1/search/**, /api/v1/web-api/v3/api-docs/**, /api/v1/rankings/live,
              /api/v1/auth/login, /api/v1/auth/refresh, /api/v1/auth/oauth2/**,
              /login/oauth2/code/**, /api/v1/members/availability/**

        - id: web-api-service-user
          uri: lb://web-api-service
          predicates:
            - Path=/api/v1/posts/**, /api/v1/comments/**, /api/v1/likes/**, /api/v1/search/*/me, /api/v1/members/**, /api/v1/auth/**
          filters:
            - name: JwtAuthenticationFilter

        - id: web-api-service-admin
          uri: lb://web-api-service
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - name: JwtAuthenticationFilter
            - name: RoleAuthorizationFilter
              args:
                requiredRole: ROLE_ADMIN


        - id: post-service-docs
          uri: lb://post-service
          predicates:
            - Path=/v1/posts/v3/api-docs/**

        - id: search-service-docs
          uri: lb://search-service
          predicates:
            - Path=/v1/search/v3/api-docs/**

        - id: member-service-docs
          uri: lb://member-service
          predicates:
            - Path=/v1/members/v3/api-docs/**


      httpclient:
        connect-timeout: 5000
        response-timeout: 5s

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:3000}
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "Authorization"
              - "Set-Cookie"
            allowedMethods:
              - "GET"
              - "POST"
              - "DELETE"
              - "PUT"
              - "PATCH"
              - "OPTIONS"
            allowCredentials: true
            maxAge: 3600


eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVERS}/eureka

#security key
app:
  jwt:
    secret: ${JWT_SECRET_KEY}

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Web Api Service
        url: /api/v1/web-api/v3/api-docs/web-api-service
      - name: Post Service Docs
        url: /v1/posts/v3/api-docs/post-service
      - name: Search Service Docs
        url: /v1/search/v3/api-docs/search-service
      - name: Member Service Docs
        url: /v1/members/v3/api-docs/member-service
