server:
  port: 8001
  forward-headers-strategy: framework

spring:
  application:
    name: "web-api-service"

  config:
    import: optional:file:web-api-service/.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}          # 카카오 디벨로퍼스에서 발급받은 REST API 키
            client-secret: ${KAKAO_CLIENT_SECRET}  # (선택 사항이나 보안상 활성화 권장)
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" # 카카오 디벨로퍼스 설정과 일치해야 함
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 카카오 사용자 정보의 Key값 (기본 id)

swagger:
  info:
    paths-to-match:
      - "/api/v1/**"

springdoc:
  api-docs:
    path: /api/v1/web-api/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  use-fqn: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVERS}/eureka

app:
  jwt:
    refresh-expiration: ${JWT_REFRESH_EXPIRATION:1209600000} # 14일
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  frontend:
    redirect-uri: ${FRONTEND_REDIRECT_URI:http://localhost:3000/oauth2/redirect}

  cookie:
    secure: true
