server:
  port: 1236  # 임시
  forward-headers-strategy: framework

spring:
  application:
    name: "web-api-service"

  config:
    import: optional:file:web-api-service/.env[.properties]

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

swagger:
  info:
    paths-to-match:
      - "/api/v1/**"

springdoc:
  api-docs:
    path: /api/v1/posts/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
