server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: board
          uri: lb://board/
          predicates:
            - Path=/board/**
        - id: sign-api
          uri: lb://sign-api/
          predicates:
            - Path=/sign-api/**, /kafka/**
        - id: logpipeline
          uri: lb://logpipeline/
          predicates:
            - Path=/format/**, /sse/**, /process/**, /filter/**, /log-db/**, /deduplication/**
        - id: comment
          uri: lb://comment/
          predicates:
            - Path=/comment-api/**
        - id: favorite
          uri: lb://favorite
          predicates:
            - Path=/favorite-api/**
        - id: realtimepopular
          uri: lb://realtimepopular
          predicates:
            - Path=/realtime-popular/**
        - id: bff
          uri: lb://bff
          predicates:
            - Path=/api/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
            allowCredentials: true


eureka:
  client:
    register-with-eureka: true # ?? ??? ???? ???? ??
    fetch-registry: true # ??????? ???? ??? ??? ??? ??? ??. ??? ?? ?? ??.
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

#security key
springboot:
  jwt:
    secret: qwertyuiopasdfghjklzxcvbnm!qwertyuiopasdfghjklzxcvbnm
