server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  codec:
    max-in-memory-size: 20MB
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        max-initial-line-length: 8192
        max-header-size: 16384
        max-request-size: 20MB
      routes:
        - id: board
          uri: lb://board/
          predicates:
            - Path=/board/**
        - id: realtimepopular
          uri: lb://realtimepopular
          predicates:
            - Path=/realtime-popular/**
        - id: bff
          uri: lb://bff
          predicates:
            - Path=/api/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://14.63.178.161"
            allowedHeaders:
              - "*"
            allowedMethods:
              - "GET"
              - "POST"
              - "OPTIONS"
            allowCredentials: true


eureka:
  client:
    register-with-eureka: true # ?? ??? ???? ???? ??
    fetch-registry: true # ??????? ???? ??? ??? ??? ??? ??. ??? ?? ?? ??.
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

#security key
springboot:
  jwt:
    secret: qwertyuiopasdfghjklzxcvbnm!qwertyuiopasdfghjklzxcvbnm
