server:
  port: 8001

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  codec:
    max-in-memory-size: 20MB
  application:
    name: bff

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

board:
  ribbon:
    eureka:
      enabled: true
sign:
  ribbon:
    eureka:
      enabled: true
logpipeline:
  ribbon:
    eureka:
      enabled: true
comment:
  ribbon:
    eureka:
      enabled: true
favorite:
  ribbon:
    eureka:
      enabled: true

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
    register-with-eureka: true
    fetch-registry: true

